language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- ./internal/scripts/support/setup.sh && pip install github3.py
script:
- make build_for_gh_pages
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
  - secure: iKuVPLPN105Z/ihhnqg12wr08RcHHXvJDj1UAwXLVw0O7gnldi5+LaFkM3hNA0jw8WCY4pHgn/dfcWgU5FrzX0F9pIMzOQ+vYSclfE80kWROHERQ9H/opaYLT4ZqSc5d3xs7gQeAgk5dG/Z/LItWxJdm0QC/nj5gHPcZlU86iiQ=
after_success: >
    ./internal/scripts/support/upload_to_csplib-builds.sh
